// routes.ts
const ROUTES = {
  HOME: '/',
  CATEGORY: '/category',
  BRAND: '/brand',
  PRODUCTS: '/products',
  PRODUCT_CREATE: '/products/create',
  PRODUCT_EDIT: (slug: string, productId: string) => `/products/edit/${slug}/${productId}`,
  PRODUCT_SHOW: (slug: string, productId: string) => `/products/${slug}/${productId}`,
  INVENTORY_CONTROL: '/inventory-control',
  INVENTORY_MOVEMENTS: '/inventory-movements',
  INVENTORY_EXPORT: '/i/transactions/export-inventory-excel/',
  PURCHASE_LIST: '/purchase/list',
  PURCHASE_CREATE: '/purchase/create',
  PURCHASE_SHOW: (purchaseId: string) => `/purchase/${purchaseId}`,
  SUPPLIERS: '/suppliers',
  SUPPLIER_FORM: '/suppliers/form',
  SUPPLIER_EDIT: (supplierId: string) => `/suppliers/form/${supplierId}`,
  SUPPLIER_EXPORT: '/s/suppliers/supplier-export-excel/',
  SALE_LIST: '/sale/list',
  SALE_CREATE: '/sale/create',
  SALE_SHOW: (saleId: string) => `/sale/${saleId}`,
  SALE_RECEIPT: (saleId: string) => `/sale/${saleId}/receipt`,
  CUSTOMERS_LIST: '/customers/list',
  CUSTOMER_FORM: '/customers/form',
  CUSTOMER_EDIT: (customerId: string) => `/customers/form/${customerId}`,
  CUSTOMER_EXPORT: 'c/customers/customer-export-excel/',
  ACCOUNT: '/account',
  SETTING: '/setting',
  WAREHOUSE: '/warehouse',
  PROFILE: '/profile',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  NOT_FOUND: '*',
}

export default ROUTES
